# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QC_Charts.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Pie_Chart_widget = QtWidgets.QWidget(self.centralwidget)
        self.Pie_Chart_widget.setObjectName("Pie_Chart_widget")
        self.gridLayout.addWidget(self.Pie_Chart_widget, 0, 0, 1, 1)
        self.Bar_Chart_widget = QtWidgets.QWidget(self.centralwidget)
        self.Bar_Chart_widget.setObjectName("Bar_Chart_widget")
        self.gridLayout.addWidget(self.Bar_Chart_widget, 0, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(638, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.Back_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Back_pushButton.setObjectName("Back_pushButton")
        self.gridLayout.addWidget(self.Back_pushButton, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Back_pushButton.setText(_translate("MainWindow", "Back"))
